#!/bin/bash

interface="$1"

if [ -z "$interface" ]; then
  echo "No target interface/link given"
  exit 1
fi

cidr_broadcast=$(ifconfig "$interface" | grep broadcast | awk '{print $NF}')
cidr_block="${link_cider_block%.*}.0"

nmap -sn "$cidr_block"

docker rm -f nginx-reverse-proxy

docker run --name nginx-reverse-proxy \
  -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
  --net=host nginx:1.21.1-alpine
