#!/bin/bash -e

interface=$1

echo "Starting to stupidly set hostname based on $interface..."

ip=$(ifconfig "$interface" | grep broadcast | awk '{print $2}')
if [ -z "$ip" ]; then
  exit 1
fi
hostname="rpi-$ip"

echo "Setting hostname to '$hostname'"

hostnamectl set-hostname "$hostname"
