#!/bin/sh

interface=$1
wpa_conf=$2

if [ -z "$wpa_conf" ]; then
  wpa_conf=/etc/wpa_supplicant/wpa_supplicant.conf
  echo "No WPA Conf path provided, defaulting to $wpa_conf"
fi

if [ -z "$interface" ]; then
  interface="wlan0"
  echo "No network device provided, defaulting to $interface"
fi

wpa_supplicant -Bc "$wpa_conf" -i "$interface"
dhclient "$interface"
